version: "2"

linters:
  default: none
  enable:
    - gosec          # Security scanner (replaces separate gosec stage)
    - errcheck       # Check for unchecked errors
    - govet          # Go vet
    - staticcheck    # Static analysis
    - ineffassign    # Detect unused assignments
    - unused         # Detect unused code
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      # Ignore errcheck and gosec in test files
      - path: _test\.go$
        linters:
          - errcheck
          - gosec

run:
  timeout: 5m
