version: "2"

linters:
  enable:
    - gosec          # Security scanner (replaces separate gosec stage)
    - errcheck       # Check for unchecked errors
    - govet          # Go vet
    - staticcheck    # Static analysis
    - ineffassign    # Detect unused assignments
    - unused         # Detect unused code

linters-settings:
  gosec:
    excludes:
      - G104  # Audit errors not checked (we use //nolint for intentional cases)

run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    # Ignore errcheck and gosec in test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
